# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doris/doris.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 856)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lb_frames = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_frames.setFont(font)
        self.lb_frames.setText("")
        self.lb_frames.setObjectName("lb_frames")
        self.verticalLayout_6.addWidget(self.lb_frames)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_1st_frame = QtWidgets.QPushButton(self.centralwidget)
        self.pb_1st_frame.setObjectName("pb_1st_frame")
        self.horizontalLayout_5.addWidget(self.pb_1st_frame)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.le_goto_frame = QtWidgets.QLineEdit(self.centralwidget)
        self.le_goto_frame.setObjectName("le_goto_frame")
        self.horizontalLayout_5.addWidget(self.le_goto_frame)
        self.pb_goto_frame = QtWidgets.QPushButton(self.centralwidget)
        self.pb_goto_frame.setObjectName("pb_goto_frame")
        self.horizontalLayout_5.addWidget(self.pb_goto_frame)
        self.lb_start_from = QtWidgets.QLabel(self.centralwidget)
        self.lb_start_from.setObjectName("lb_start_from")
        self.horizontalLayout_5.addWidget(self.lb_start_from)
        self.sb_start_from = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_start_from.setMaximum(1000000)
        self.sb_start_from.setObjectName("sb_start_from")
        self.horizontalLayout_5.addWidget(self.sb_start_from)
        self.lb_stop_to = QtWidgets.QLabel(self.centralwidget)
        self.lb_stop_to.setObjectName("lb_stop_to")
        self.horizontalLayout_5.addWidget(self.lb_stop_to)
        self.sb_stop_to = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_stop_to.setMaximum(1000000)
        self.sb_stop_to.setObjectName("sb_stop_to")
        self.horizontalLayout_5.addWidget(self.sb_stop_to)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.sb_frame_offset = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_frame_offset.setMinimum(1)
        self.sb_frame_offset.setMaximum(10000)
        self.sb_frame_offset.setSingleStep(10)
        self.sb_frame_offset.setProperty("value", 1)
        self.sb_frame_offset.setObjectName("sb_frame_offset")
        self.horizontalLayout_5.addWidget(self.sb_frame_offset)
        self.pb_backward = QtWidgets.QPushButton(self.centralwidget)
        self.pb_backward.setObjectName("pb_backward")
        self.horizontalLayout_5.addWidget(self.pb_backward)
        self.pb_forward = QtWidgets.QPushButton(self.centralwidget)
        self.pb_forward.setObjectName("pb_forward")
        self.horizontalLayout_5.addWidget(self.pb_forward)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.tb_minus10 = QtWidgets.QToolButton(self.centralwidget)
        self.tb_minus10.setObjectName("tb_minus10")
        self.horizontalLayout_5.addWidget(self.tb_minus10)
        self.tb_minus1 = QtWidgets.QToolButton(self.centralwidget)
        self.tb_minus1.setObjectName("tb_minus1")
        self.horizontalLayout_5.addWidget(self.tb_minus1)
        self.tb_plus1 = QtWidgets.QToolButton(self.centralwidget)
        self.tb_plus1.setObjectName("tb_plus1")
        self.horizontalLayout_5.addWidget(self.tb_plus1)
        self.tb_plus10 = QtWidgets.QToolButton(self.centralwidget)
        self.tb_plus10.setObjectName("tb_plus10")
        self.horizontalLayout_5.addWidget(self.tb_plus10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.hs_frame = QtWidgets.QSlider(self.centralwidget)
        self.hs_frame.setOrientation(QtCore.Qt.Horizontal)
        self.hs_frame.setObjectName("hs_frame")
        self.verticalLayout_6.addWidget(self.hs_frame)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.sb_blur = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_blur.setProperty("value", 2)
        self.sb_blur.setObjectName("sb_blur")
        self.horizontalLayout_10.addWidget(self.sb_blur)
        self.cb_invert = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_invert.setObjectName("cb_invert")
        self.horizontalLayout_10.addWidget(self.cb_invert)
        self.cb_background = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_background.setEnabled(False)
        self.cb_background.setObjectName("cb_background")
        self.horizontalLayout_10.addWidget(self.cb_background)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.cb_threshold_method = QtWidgets.QComboBox(self.centralwidget)
        self.cb_threshold_method.setObjectName("cb_threshold_method")
        self.cb_threshold_method.addItem("")
        self.cb_threshold_method.addItem("")
        self.cb_threshold_method.addItem("")
        self.horizontalLayout_10.addWidget(self.cb_threshold_method)
        self.lb_threshold = QtWidgets.QLabel(self.centralwidget)
        self.lb_threshold.setObjectName("lb_threshold")
        self.horizontalLayout_10.addWidget(self.lb_threshold)
        self.sb_threshold = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_threshold.setMaximum(255)
        self.sb_threshold.setObjectName("sb_threshold")
        self.horizontalLayout_10.addWidget(self.sb_threshold)
        self.lb_adaptive_threshold = QtWidgets.QLabel(self.centralwidget)
        self.lb_adaptive_threshold.setObjectName("lb_adaptive_threshold")
        self.horizontalLayout_10.addWidget(self.lb_adaptive_threshold)
        self.lb_block_size = QtWidgets.QLabel(self.centralwidget)
        self.lb_block_size.setObjectName("lb_block_size")
        self.horizontalLayout_10.addWidget(self.lb_block_size)
        self.sb_block_size = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_block_size.setProperty("value", 10)
        self.sb_block_size.setObjectName("sb_block_size")
        self.horizontalLayout_10.addWidget(self.sb_block_size)
        self.lb_offset = QtWidgets.QLabel(self.centralwidget)
        self.lb_offset.setObjectName("lb_offset")
        self.horizontalLayout_10.addWidget(self.lb_offset)
        self.sb_offset = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_offset.setProperty("value", 10)
        self.sb_offset.setObjectName("sb_offset")
        self.horizontalLayout_10.addWidget(self.sb_offset)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_16.addWidget(self.label_5)
        self.pb_define_arena = QtWidgets.QPushButton(self.centralwidget)
        self.pb_define_arena.setObjectName("pb_define_arena")
        self.horizontalLayout_16.addWidget(self.pb_define_arena)
        self.pb_clear_arena = QtWidgets.QPushButton(self.centralwidget)
        self.pb_clear_arena.setEnabled(False)
        self.pb_clear_arena.setObjectName("pb_clear_arena")
        self.horizontalLayout_16.addWidget(self.pb_clear_arena)
        self.le_arena = QtWidgets.QLineEdit(self.centralwidget)
        self.le_arena.setReadOnly(True)
        self.le_arena.setObjectName("le_arena")
        self.horizontalLayout_16.addWidget(self.le_arena)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.sbMin = QtWidgets.QSpinBox(self.centralwidget)
        self.sbMin.setMaximum(100000)
        self.sbMin.setSingleStep(10)
        self.sbMin.setProperty("value", 0)
        self.sbMin.setObjectName("sbMin")
        self.horizontalLayout_2.addWidget(self.sbMin)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.sbMax = QtWidgets.QSpinBox(self.centralwidget)
        self.sbMax.setMaximum(100000)
        self.sbMax.setSingleStep(10)
        self.sbMax.setProperty("value", 0)
        self.sbMax.setObjectName("sbMax")
        self.horizontalLayout_3.addWidget(self.sbMax)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.sb_max_extension = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_max_extension.setMaximum(9999999)
        self.sb_max_extension.setSingleStep(100)
        self.sb_max_extension.setObjectName("sb_max_extension")
        self.horizontalLayout_17.addWidget(self.sb_max_extension)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.sb_max_distance = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_max_distance.setMaximum(1000)
        self.sb_max_distance.setObjectName("sb_max_distance")
        self.horizontalLayout_18.addWidget(self.sb_max_distance)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.pb_add_mask = QtWidgets.QPushButton(self.centralwidget)
        self.pb_add_mask.setObjectName("pb_add_mask")
        self.verticalLayout_3.addWidget(self.pb_add_mask)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lw_masks = QtWidgets.QListWidget(self.centralwidget)
        self.lw_masks.setObjectName("lw_masks")
        self.verticalLayout_3.addWidget(self.lw_masks)
        spacerItem5 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_21.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_all = QtWidgets.QLabel(self.centralwidget)
        self.lb_all.setObjectName("lb_all")
        self.verticalLayout.addWidget(self.lb_all)
        self.te_all_objects = QtWidgets.QTextEdit(self.centralwidget)
        self.te_all_objects.setReadOnly(True)
        self.te_all_objects.setObjectName("te_all_objects")
        self.verticalLayout.addWidget(self.te_all_objects)
        self.pb_show_all_objects = QtWidgets.QPushButton(self.centralwidget)
        self.pb_show_all_objects.setObjectName("pb_show_all_objects")
        self.verticalLayout.addWidget(self.pb_show_all_objects)
        self.horizontalLayout_21.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_filtered = QtWidgets.QLabel(self.centralwidget)
        self.lb_filtered.setObjectName("lb_filtered")
        self.verticalLayout_2.addWidget(self.lb_filtered)
        self.te_filtered_objects = QtWidgets.QTextEdit(self.centralwidget)
        self.te_filtered_objects.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.te_filtered_objects.setReadOnly(True)
        self.te_filtered_objects.setObjectName("te_filtered_objects")
        self.verticalLayout_2.addWidget(self.te_filtered_objects)
        self.pb_show_all_filtered_objects = QtWidgets.QPushButton(self.centralwidget)
        self.pb_show_all_filtered_objects.setObjectName("pb_show_all_filtered_objects")
        self.verticalLayout_2.addWidget(self.pb_show_all_filtered_objects)
        self.pb_separate_objects = QtWidgets.QPushButton(self.centralwidget)
        self.pb_separate_objects.setObjectName("pb_separate_objects")
        self.verticalLayout_2.addWidget(self.pb_separate_objects)
        self.horizontalLayout_21.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lb_tracked_objects = QtWidgets.QLabel(self.centralwidget)
        self.lb_tracked_objects.setObjectName("lb_tracked_objects")
        self.verticalLayout_4.addWidget(self.lb_tracked_objects)
        self.te_tracked_objects = QtWidgets.QTextEdit(self.centralwidget)
        self.te_tracked_objects.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.te_tracked_objects.setReadOnly(True)
        self.te_tracked_objects.setObjectName("te_tracked_objects")
        self.verticalLayout_4.addWidget(self.te_tracked_objects)
        self.pb_select_objects_to_track = QtWidgets.QPushButton(self.centralwidget)
        self.pb_select_objects_to_track.setObjectName("pb_select_objects_to_track")
        self.verticalLayout_4.addWidget(self.pb_select_objects_to_track)
        self.pb_track_all_filtered = QtWidgets.QPushButton(self.centralwidget)
        self.pb_track_all_filtered.setObjectName("pb_track_all_filtered")
        self.verticalLayout_4.addWidget(self.pb_track_all_filtered)
        self.pb_repick_objects = QtWidgets.QPushButton(self.centralwidget)
        self.pb_repick_objects.setObjectName("pb_repick_objects")
        self.verticalLayout_4.addWidget(self.pb_repick_objects)
        self.pb_repick_objects_from_all = QtWidgets.QPushButton(self.centralwidget)
        self.pb_repick_objects_from_all.setObjectName("pb_repick_objects_from_all")
        self.verticalLayout_4.addWidget(self.pb_repick_objects_from_all)
        self.horizontalLayout_21.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.tab_tracking_results = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_tracking_results.setObjectName("tab_tracking_results")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.le_coordinates_center = QtWidgets.QLineEdit(self.tab)
        self.le_coordinates_center.setReadOnly(True)
        self.le_coordinates_center.setObjectName("le_coordinates_center")
        self.horizontalLayout_11.addWidget(self.le_coordinates_center)
        self.pb_define_origin = QtWidgets.QPushButton(self.tab)
        self.pb_define_origin.setObjectName("pb_define_origin")
        self.horizontalLayout_11.addWidget(self.pb_define_origin)
        self.pb_reset_origin = QtWidgets.QPushButton(self.tab)
        self.pb_reset_origin.setObjectName("pb_reset_origin")
        self.horizontalLayout_11.addWidget(self.pb_reset_origin)
        self.cb_apply_origin = QtWidgets.QCheckBox(self.tab)
        self.cb_apply_origin.setObjectName("cb_apply_origin")
        self.horizontalLayout_11.addWidget(self.cb_apply_origin)
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.le_scale = QtWidgets.QLineEdit(self.tab)
        self.le_scale.setEnabled(True)
        self.le_scale.setReadOnly(True)
        self.le_scale.setObjectName("le_scale")
        self.horizontalLayout_11.addWidget(self.le_scale)
        self.pb_define_scale = QtWidgets.QPushButton(self.tab)
        self.pb_define_scale.setObjectName("pb_define_scale")
        self.horizontalLayout_11.addWidget(self.pb_define_scale)
        self.pb_reset_scale = QtWidgets.QPushButton(self.tab)
        self.pb_reset_scale.setObjectName("pb_reset_scale")
        self.horizontalLayout_11.addWidget(self.pb_reset_scale)
        self.cb_apply_scale = QtWidgets.QCheckBox(self.tab)
        self.cb_apply_scale.setObjectName("cb_apply_scale")
        self.horizontalLayout_11.addWidget(self.cb_apply_scale)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_record_xy = QtWidgets.QCheckBox(self.tab)
        self.cb_record_xy.setObjectName("cb_record_xy")
        self.horizontalLayout_4.addWidget(self.cb_record_xy)
        self.cb_normalize_coordinates = QtWidgets.QCheckBox(self.tab)
        self.cb_normalize_coordinates.setEnabled(False)
        self.cb_normalize_coordinates.setObjectName("cb_normalize_coordinates")
        self.horizontalLayout_4.addWidget(self.cb_normalize_coordinates)
        self.cb_reset_following_coordinates = QtWidgets.QCheckBox(self.tab)
        self.cb_reset_following_coordinates.setChecked(True)
        self.cb_reset_following_coordinates.setObjectName("cb_reset_following_coordinates")
        self.horizontalLayout_4.addWidget(self.cb_reset_following_coordinates)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.te_xy = QtWidgets.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.te_xy.setFont(font)
        self.te_xy.setReadOnly(True)
        self.te_xy.setObjectName("te_xy")
        self.verticalLayout_5.addWidget(self.te_xy)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pb_save_xy = QtWidgets.QPushButton(self.tab)
        self.pb_save_xy.setObjectName("pb_save_xy")
        self.horizontalLayout_12.addWidget(self.pb_save_xy)
        self.pb_view_coordinates = QtWidgets.QPushButton(self.tab)
        self.pb_view_coordinates.setObjectName("pb_view_coordinates")
        self.horizontalLayout_12.addWidget(self.pb_view_coordinates)
        self.pb_delete_coordinates = QtWidgets.QPushButton(self.tab)
        self.pb_delete_coordinates.setObjectName("pb_delete_coordinates")
        self.horizontalLayout_12.addWidget(self.pb_delete_coordinates)
        self.pb_plot_path = QtWidgets.QPushButton(self.tab)
        self.pb_plot_path.setObjectName("pb_plot_path")
        self.horizontalLayout_12.addWidget(self.pb_plot_path)
        self.pb_plot_positions = QtWidgets.QPushButton(self.tab)
        self.pb_plot_positions.setObjectName("pb_plot_positions")
        self.horizontalLayout_12.addWidget(self.pb_plot_positions)
        self.pb_plot_xy_density = QtWidgets.QPushButton(self.tab)
        self.pb_plot_xy_density.setObjectName("pb_plot_xy_density")
        self.horizontalLayout_12.addWidget(self.pb_plot_xy_density)
        self.pb_distances = QtWidgets.QPushButton(self.tab)
        self.pb_distances.setObjectName("pb_distances")
        self.horizontalLayout_12.addWidget(self.pb_distances)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.tab_tracking_results.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cb_record_presence_area = QtWidgets.QCheckBox(self.tab_2)
        self.cb_record_presence_area.setObjectName("cb_record_presence_area")
        self.verticalLayout_7.addWidget(self.cb_record_presence_area)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.lw_area_definition = QtWidgets.QListWidget(self.tab_2)
        self.lw_area_definition.setObjectName("lw_area_definition")
        self.verticalLayout_7.addWidget(self.lw_area_definition)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pb_add_area = QtWidgets.QPushButton(self.tab_2)
        self.pb_add_area.setObjectName("pb_add_area")
        self.horizontalLayout_13.addWidget(self.pb_add_area)
        self.pb_remove_area = QtWidgets.QPushButton(self.tab_2)
        self.pb_remove_area.setObjectName("pb_remove_area")
        self.horizontalLayout_13.addWidget(self.pb_remove_area)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.te_number_objects = QtWidgets.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.te_number_objects.setFont(font)
        self.te_number_objects.setReadOnly(True)
        self.te_number_objects.setObjectName("te_number_objects")
        self.verticalLayout_8.addWidget(self.te_number_objects)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pb_delete_area_analysis = QtWidgets.QPushButton(self.tab_2)
        self.pb_delete_area_analysis.setObjectName("pb_delete_area_analysis")
        self.horizontalLayout_14.addWidget(self.pb_delete_area_analysis)
        self.pb_save_objects_number = QtWidgets.QPushButton(self.tab_2)
        self.pb_save_objects_number.setObjectName("pb_save_objects_number")
        self.horizontalLayout_14.addWidget(self.pb_save_objects_number)
        self.pb_time_in_areas = QtWidgets.QPushButton(self.tab_2)
        self.pb_time_in_areas.setObjectName("pb_time_in_areas")
        self.horizontalLayout_14.addWidget(self.pb_time_in_areas)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.tab_tracking_results.addTab(self.tab_2, "")
        self.verticalLayout_6.addWidget(self.tab_tracking_results)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_continue_when_no_objects = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_continue_when_no_objects.setObjectName("cb_continue_when_no_objects")
        self.horizontalLayout.addWidget(self.cb_continue_when_no_objects)
        self.cb_display_analysis = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_display_analysis.setChecked(True)
        self.cb_display_analysis.setObjectName("cb_display_analysis")
        self.horizontalLayout.addWidget(self.cb_display_analysis)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setEnabled(False)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.sb_display_frequency = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_display_frequency.setEnabled(False)
        self.sb_display_frequency.setMinimum(1)
        self.sb_display_frequency.setMaximum(1000)
        self.sb_display_frequency.setObjectName("sb_display_frequency")
        self.horizontalLayout.addWidget(self.sb_display_frequency)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_run_tracking = QtWidgets.QPushButton(self.centralwidget)
        self.pb_run_tracking.setCheckable(True)
        self.pb_run_tracking.setObjectName("pb_run_tracking")
        self.horizontalLayout_6.addWidget(self.pb_run_tracking)
        self.pb_run_tracking_frame_interval = QtWidgets.QPushButton(self.centralwidget)
        self.pb_run_tracking_frame_interval.setCheckable(True)
        self.pb_run_tracking_frame_interval.setObjectName("pb_run_tracking_frame_interval")
        self.horizontalLayout_6.addWidget(self.pb_run_tracking_frame_interval)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuFrame_viewer_scale = QtWidgets.QMenu(self.menuSettings)
        self.menuFrame_viewer_scale.setObjectName("menuFrame_viewer_scale")
        self.menuTreatment_viewer_scale = QtWidgets.QMenu(self.menuSettings)
        self.menuTreatment_viewer_scale.setObjectName("menuTreatment_viewer_scale")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_video = QtWidgets.QAction(MainWindow)
        self.actionOpen_video.setObjectName("actionOpen_video")
        self.actionBackground = QtWidgets.QAction(MainWindow)
        self.actionBackground.setObjectName("actionBackground")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFrame_width = QtWidgets.QAction(MainWindow)
        self.actionFrame_width.setObjectName("actionFrame_width")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_directory_of_images = QtWidgets.QAction(MainWindow)
        self.actionLoad_directory_of_images.setObjectName("actionLoad_directory_of_images")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action1_4 = QtWidgets.QAction(MainWindow)
        self.action1_4.setObjectName("action1_4")
        self.action_treated_1 = QtWidgets.QAction(MainWindow)
        self.action_treated_1.setObjectName("action_treated_1")
        self.action_treated_1_2 = QtWidgets.QAction(MainWindow)
        self.action_treated_1_2.setObjectName("action_treated_1_2")
        self.action_treated_1_4 = QtWidgets.QAction(MainWindow)
        self.action_treated_1_4.setObjectName("action_treated_1_4")
        self.actionSave_project = QtWidgets.QAction(MainWindow)
        self.actionSave_project.setObjectName("actionSave_project")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action_treated_2 = QtWidgets.QAction(MainWindow)
        self.action_treated_2.setObjectName("action_treated_2")
        self.actionOpen_project = QtWidgets.QAction(MainWindow)
        self.actionOpen_project.setObjectName("actionOpen_project")
        self.actionDraw_reference = QtWidgets.QAction(MainWindow)
        self.actionDraw_reference.setCheckable(True)
        self.actionDraw_reference.setObjectName("actionDraw_reference")
        self.actionSelect_objects_to_track = QtWidgets.QAction(MainWindow)
        self.actionSelect_objects_to_track.setCheckable(False)
        self.actionSelect_objects_to_track.setObjectName("actionSelect_objects_to_track")
        self.actionDefine_scale = QtWidgets.QAction(MainWindow)
        self.actionDefine_scale.setObjectName("actionDefine_scale")
        self.actionOrigin_from_point = QtWidgets.QAction(MainWindow)
        self.actionOrigin_from_point.setObjectName("actionOrigin_from_point")
        self.actionOrigin_from_center_of_3_points_circle = QtWidgets.QAction(MainWindow)
        self.actionOrigin_from_center_of_3_points_circle.setObjectName("actionOrigin_from_center_of_3_points_circle")
        self.actionShow_centroid_of_object = QtWidgets.QAction(MainWindow)
        self.actionShow_centroid_of_object.setCheckable(True)
        self.actionShow_centroid_of_object.setObjectName("actionShow_centroid_of_object")
        self.actionShow_contour_of_object = QtWidgets.QAction(MainWindow)
        self.actionShow_contour_of_object.setCheckable(True)
        self.actionShow_contour_of_object.setChecked(True)
        self.actionShow_contour_of_object.setObjectName("actionShow_contour_of_object")
        self.actionSave_project_as = QtWidgets.QAction(MainWindow)
        self.actionSave_project_as.setObjectName("actionSave_project_as")
        self.actionShow_object_path = QtWidgets.QAction(MainWindow)
        self.actionShow_object_path.setCheckable(True)
        self.actionShow_object_path.setObjectName("actionShow_object_path")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addAction(self.actionOpen_project)
        self.menuFile.addAction(self.actionSave_project)
        self.menuFile.addAction(self.actionSave_project_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_video)
        self.menuFile.addAction(self.actionLoad_directory_of_images)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFrame_viewer_scale.addAction(self.action2)
        self.menuFrame_viewer_scale.addAction(self.action1)
        self.menuFrame_viewer_scale.addAction(self.action1_2)
        self.menuFrame_viewer_scale.addAction(self.action1_4)
        self.menuTreatment_viewer_scale.addAction(self.action_treated_2)
        self.menuTreatment_viewer_scale.addAction(self.action_treated_1)
        self.menuTreatment_viewer_scale.addAction(self.action_treated_1_2)
        self.menuTreatment_viewer_scale.addAction(self.action_treated_1_4)
        self.menuSettings.addAction(self.menuFrame_viewer_scale.menuAction())
        self.menuSettings.addAction(self.menuTreatment_viewer_scale.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionDraw_reference)
        self.menuView.addAction(self.actionShow_centroid_of_object)
        self.menuView.addAction(self.actionShow_contour_of_object)
        self.menuView.addAction(self.actionShow_object_path)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_tracking_results.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_1st_frame.setText(_translate("MainWindow", "Reset"))
        self.label_11.setText(_translate("MainWindow", "frame number"))
        self.le_goto_frame.setText(_translate("MainWindow", "1"))
        self.pb_goto_frame.setText(_translate("MainWindow", "Go to"))
        self.lb_start_from.setText(_translate("MainWindow", "Start from"))
        self.lb_stop_to.setText(_translate("MainWindow", "Stop to"))
        self.label_10.setText(_translate("MainWindow", "Step"))
        self.pb_backward.setText(_translate("MainWindow", "go backward"))
        self.pb_forward.setText(_translate("MainWindow", "go forward"))
        self.label_16.setText(_translate("MainWindow", "Hold down:"))
        self.tb_minus10.setText(_translate("MainWindow", "-10"))
        self.tb_minus1.setText(_translate("MainWindow", "-1"))
        self.tb_plus1.setText(_translate("MainWindow", "+1"))
        self.tb_plus10.setText(_translate("MainWindow", "+10"))
        self.label_9.setText(_translate("MainWindow", "Image processing"))
        self.label_8.setText(_translate("MainWindow", "Blur"))
        self.cb_invert.setText(_translate("MainWindow", "Invert"))
        self.cb_background.setText(_translate("MainWindow", "Substract background"))
        self.label_14.setText(_translate("MainWindow", "Threshold method"))
        self.cb_threshold_method.setItemText(0, _translate("MainWindow", "Simple"))
        self.cb_threshold_method.setItemText(1, _translate("MainWindow", "Adaptive (mean)"))
        self.cb_threshold_method.setItemText(2, _translate("MainWindow", "Adaptive (Gaussian)"))
        self.lb_threshold.setText(_translate("MainWindow", "Simple threshold: cut-off"))
        self.lb_adaptive_threshold.setText(_translate("MainWindow", "Adaptive threshold:"))
        self.lb_block_size.setText(_translate("MainWindow", "Block size"))
        self.lb_offset.setText(_translate("MainWindow", "Offset"))
        self.label_5.setText(_translate("MainWindow", "Objects"))
        self.pb_define_arena.setText(_translate("MainWindow", "Define arena"))
        self.pb_clear_arena.setText(_translate("MainWindow", "Clear arena"))
        self.label_3.setText(_translate("MainWindow", "min obj size"))
        self.label_4.setText(_translate("MainWindow", "max obj size"))
        self.label_13.setText(_translate("MainWindow", "Max object extension"))
        self.label_22.setText(_translate("MainWindow", "Max distance between frames (pixels)"))
        self.pb_add_mask.setText(_translate("MainWindow", "Add mask"))
        self.label_7.setText(_translate("MainWindow", "Masks"))
        self.lb_all.setText(_translate("MainWindow", "All detected objects"))
        self.pb_show_all_objects.setText(_translate("MainWindow", "Display all objects"))
        self.lb_filtered.setText(_translate("MainWindow", "Filtered objects"))
        self.pb_show_all_filtered_objects.setText(_translate("MainWindow", "Display all filtered objects"))
        self.pb_separate_objects.setText(_translate("MainWindow", "Force objects number"))
        self.lb_tracked_objects.setText(_translate("MainWindow", "Tracked objects"))
        self.pb_select_objects_to_track.setText(_translate("MainWindow", "Select objects to track"))
        self.pb_track_all_filtered.setText(_translate("MainWindow", "Track all filtered objects"))
        self.pb_repick_objects.setText(_translate("MainWindow", "Repick objects from image"))
        self.pb_repick_objects_from_all.setText(_translate("MainWindow", "Repick objects from all objects"))
        self.label_12.setText(_translate("MainWindow", "Tracking"))
        self.label.setText(_translate("MainWindow", "Origin of referential system"))
        self.pb_define_origin.setText(_translate("MainWindow", "Define origin"))
        self.pb_reset_origin.setText(_translate("MainWindow", "Reset origin"))
        self.cb_apply_origin.setText(_translate("MainWindow", "Apply origin to coordinates"))
        self.label_21.setText(_translate("MainWindow", "Scale (Units/pixel)"))
        self.le_scale.setText(_translate("MainWindow", "1"))
        self.pb_define_scale.setText(_translate("MainWindow", "Define scale"))
        self.pb_reset_scale.setText(_translate("MainWindow", "Reset scale"))
        self.cb_apply_scale.setText(_translate("MainWindow", "Apply scale to coordinates"))
        self.cb_record_xy.setText(_translate("MainWindow", "Record objects coordinates"))
        self.cb_normalize_coordinates.setText(_translate("MainWindow", "Normalize coordinates"))
        self.cb_reset_following_coordinates.setText(_translate("MainWindow", "Reset following coordinates"))
        self.pb_save_xy.setText(_translate("MainWindow", "Export coordinates"))
        self.pb_view_coordinates.setText(_translate("MainWindow", "View coordinates"))
        self.pb_delete_coordinates.setText(_translate("MainWindow", "Delete coordinates"))
        self.pb_plot_path.setText(_translate("MainWindow", "Plot path"))
        self.pb_plot_positions.setText(_translate("MainWindow", "Plot coordinates"))
        self.pb_plot_xy_density.setText(_translate("MainWindow", "plot XY density"))
        self.pb_distances.setText(_translate("MainWindow", "Save distances"))
        self.tab_tracking_results.setTabText(self.tab_tracking_results.indexOf(self.tab), _translate("MainWindow", "Objects coordinates"))
        self.cb_record_presence_area.setText(_translate("MainWindow", "Record presence of objects(s) in areas"))
        self.label_2.setText(_translate("MainWindow", "Areas"))
        self.pb_add_area.setText(_translate("MainWindow", "Add area"))
        self.pb_remove_area.setText(_translate("MainWindow", "Remove selected area"))
        self.label_6.setText(_translate("MainWindow", "Presence of object(s) in areas"))
        self.pb_delete_area_analysis.setText(_translate("MainWindow", "Delete analysis"))
        self.pb_save_objects_number.setText(_translate("MainWindow", "Save results"))
        self.pb_time_in_areas.setText(_translate("MainWindow", "Time in areas"))
        self.tab_tracking_results.setTabText(self.tab_tracking_results.indexOf(self.tab_2), _translate("MainWindow", "Objects in areas"))
        self.cb_continue_when_no_objects.setText(_translate("MainWindow", "Continue when no objects found"))
        self.cb_display_analysis.setText(_translate("MainWindow", "Display analysis"))
        self.label_15.setText(_translate("MainWindow", "Display 1 frame every "))
        self.pb_run_tracking.setText(_translate("MainWindow", "Run tracking"))
        self.pb_run_tracking_frame_interval.setText(_translate("MainWindow", "Run tracking on frames interval"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuFrame_viewer_scale.setTitle(_translate("MainWindow", "Frame viewer scale"))
        self.menuTreatment_viewer_scale.setTitle(_translate("MainWindow", "Treatment viewer scale"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen_video.setText(_translate("MainWindow", "Open video"))
        self.actionBackground.setText(_translate("MainWindow", "background"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionFrame_width.setText(_translate("MainWindow", "Frame width"))
        self.actionAbout.setText(_translate("MainWindow", "About DORIS"))
        self.actionLoad_directory_of_images.setText(_translate("MainWindow", "Load directory of images"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action1_2.setText(_translate("MainWindow", "1/2"))
        self.action1_4.setText(_translate("MainWindow", "1/4"))
        self.action_treated_1.setText(_translate("MainWindow", "1"))
        self.action_treated_1_2.setText(_translate("MainWindow", "1/2"))
        self.action_treated_1_4.setText(_translate("MainWindow", "1/4"))
        self.actionSave_project.setText(_translate("MainWindow", "Save project"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action_treated_2.setText(_translate("MainWindow", "2"))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project"))
        self.actionDraw_reference.setText(_translate("MainWindow", "Draw reference"))
        self.actionSelect_objects_to_track.setText(_translate("MainWindow", "Select objects to track"))
        self.actionDefine_scale.setText(_translate("MainWindow", "Define scale"))
        self.actionOrigin_from_point.setText(_translate("MainWindow", "from point"))
        self.actionOrigin_from_center_of_3_points_circle.setText(_translate("MainWindow", "from center of 3 points circle"))
        self.actionShow_centroid_of_object.setText(_translate("MainWindow", "Show centroid of object"))
        self.actionShow_contour_of_object.setText(_translate("MainWindow", "Show contour of object"))
        self.actionSave_project_as.setText(_translate("MainWindow", "Save project as..."))
        self.actionShow_object_path.setText(_translate("MainWindow", "Show object path on frame"))
        self.actionNew_project.setText(_translate("MainWindow", "New project"))
