# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doris.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 1067)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        self.label1.setMinimumSize(QtCore.QSize(0, 0))
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        self.label2.setObjectName("label2")
        self.horizontalLayout.addWidget(self.label2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_total_frames_nb = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_total_frames_nb.setObjectName("lb_total_frames_nb")
        self.horizontalLayout_5.addWidget(self.lb_total_frames_nb)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.leFrame = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leFrame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leFrame.setReadOnly(True)
        self.leFrame.setObjectName("leFrame")
        self.horizontalLayout_5.addWidget(self.leFrame)
        self.pb_1st_frame = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_1st_frame.setObjectName("pb_1st_frame")
        self.horizontalLayout_5.addWidget(self.pb_1st_frame)
        self.pb_next_frame = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_next_frame.setObjectName("pb_next_frame")
        self.horizontalLayout_5.addWidget(self.pb_next_frame)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.le_goto_frame = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_goto_frame.setObjectName("le_goto_frame")
        self.horizontalLayout_5.addWidget(self.le_goto_frame)
        self.pb_goto_frame = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_goto_frame.setObjectName("pb_goto_frame")
        self.horizontalLayout_5.addWidget(self.pb_goto_frame)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.sb_frame_offset = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sb_frame_offset.setMinimum(1)
        self.sb_frame_offset.setMaximum(10000)
        self.sb_frame_offset.setSingleStep(10)
        self.sb_frame_offset.setProperty("value", 10)
        self.sb_frame_offset.setObjectName("sb_frame_offset")
        self.horizontalLayout_5.addWidget(self.sb_frame_offset)
        self.pb_backward = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_backward.setObjectName("pb_backward")
        self.horizontalLayout_5.addWidget(self.pb_backward)
        self.pb_forward = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_forward.setObjectName("pb_forward")
        self.horizontalLayout_5.addWidget(self.pb_forward)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_threshold = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_threshold.setObjectName("lb_threshold")
        self.horizontalLayout_4.addWidget(self.lb_threshold)
        self.sb_threshold = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sb_threshold.setMaximum(255)
        self.sb_threshold.setObjectName("sb_threshold")
        self.horizontalLayout_4.addWidget(self.sb_threshold)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.sb_blur = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sb_blur.setProperty("value", 2)
        self.sb_blur.setObjectName("sb_blur")
        self.horizontalLayout_10.addWidget(self.sb_blur)
        self.cb_invert = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cb_invert.setObjectName("cb_invert")
        self.horizontalLayout_10.addWidget(self.cb_invert)
        self.cb_background = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cb_background.setObjectName("cb_background")
        self.horizontalLayout_10.addWidget(self.cb_background)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pb_define_arena = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_define_arena.setObjectName("pb_define_arena")
        self.horizontalLayout_16.addWidget(self.pb_define_arena)
        self.pb_clear_arena = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_clear_arena.setEnabled(False)
        self.pb_clear_arena.setObjectName("pb_clear_arena")
        self.horizontalLayout_16.addWidget(self.pb_clear_arena)
        self.le_arena = QtWidgets.QLineEdit(self.layoutWidget1)
        self.le_arena.setReadOnly(True)
        self.le_arena.setObjectName("le_arena")
        self.horizontalLayout_16.addWidget(self.le_arena)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.sbMin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sbMin.setMaximum(100000)
        self.sbMin.setSingleStep(10)
        self.sbMin.setProperty("value", 0)
        self.sbMin.setObjectName("sbMin")
        self.horizontalLayout_2.addWidget(self.sbMin)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.sbMax = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sbMax.setMaximum(100000)
        self.sbMax.setSingleStep(10)
        self.sbMax.setProperty("value", 0)
        self.sbMax.setObjectName("sbMax")
        self.horizontalLayout_3.addWidget(self.sbMax)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.sb_largest_number = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sb_largest_number.setMaximum(999)
        self.sb_largest_number.setObjectName("sb_largest_number")
        self.horizontalLayout_7.addWidget(self.sb_largest_number)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.sb_max_extension = QtWidgets.QSpinBox(self.layoutWidget1)
        self.sb_max_extension.setMaximum(999)
        self.sb_max_extension.setObjectName("sb_max_extension")
        self.horizontalLayout_17.addWidget(self.sb_max_extension)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_all = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_all.setObjectName("lb_all")
        self.verticalLayout.addWidget(self.lb_all)
        self.te_all_objects = QtWidgets.QTextEdit(self.layoutWidget1)
        self.te_all_objects.setObjectName("te_all_objects")
        self.verticalLayout.addWidget(self.te_all_objects)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_filtered = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_filtered.setObjectName("lb_filtered")
        self.verticalLayout_2.addWidget(self.lb_filtered)
        self.te_objects = QtWidgets.QTextEdit(self.layoutWidget1)
        self.te_objects.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.te_objects.setObjectName("te_objects")
        self.verticalLayout_2.addWidget(self.te_objects)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_record_xy = QtWidgets.QCheckBox(self.tab)
        self.cb_record_xy.setObjectName("cb_record_xy")
        self.verticalLayout_5.addWidget(self.cb_record_xy)
        self.te_xy = QtWidgets.QTextEdit(self.tab)
        self.te_xy.setObjectName("te_xy")
        self.verticalLayout_5.addWidget(self.te_xy)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pb_reset_xy = QtWidgets.QPushButton(self.tab)
        self.pb_reset_xy.setObjectName("pb_reset_xy")
        self.horizontalLayout_12.addWidget(self.pb_reset_xy)
        self.pb_save_xy = QtWidgets.QPushButton(self.tab)
        self.pb_save_xy.setObjectName("pb_save_xy")
        self.horizontalLayout_12.addWidget(self.pb_save_xy)
        self.pb_plot_path = QtWidgets.QPushButton(self.tab)
        self.pb_plot_path.setObjectName("pb_plot_path")
        self.horizontalLayout_12.addWidget(self.pb_plot_path)
        self.pb_plot_xy_density = QtWidgets.QPushButton(self.tab)
        self.pb_plot_xy_density.setObjectName("pb_plot_xy_density")
        self.horizontalLayout_12.addWidget(self.pb_plot_xy_density)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cb_record_number_objects = QtWidgets.QCheckBox(self.tab_2)
        self.cb_record_number_objects.setObjectName("cb_record_number_objects")
        self.verticalLayout_7.addWidget(self.cb_record_number_objects)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.lw_area_definition = QtWidgets.QListWidget(self.tab_2)
        self.lw_area_definition.setObjectName("lw_area_definition")
        self.verticalLayout_7.addWidget(self.lw_area_definition)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pb_add_area = QtWidgets.QPushButton(self.tab_2)
        self.pb_add_area.setObjectName("pb_add_area")
        self.horizontalLayout_13.addWidget(self.pb_add_area)
        self.pb_remove_area = QtWidgets.QPushButton(self.tab_2)
        self.pb_remove_area.setObjectName("pb_remove_area")
        self.horizontalLayout_13.addWidget(self.pb_remove_area)
        self.pb_open_areas = QtWidgets.QPushButton(self.tab_2)
        self.pb_open_areas.setObjectName("pb_open_areas")
        self.horizontalLayout_13.addWidget(self.pb_open_areas)
        self.pb_save_areas = QtWidgets.QPushButton(self.tab_2)
        self.pb_save_areas.setObjectName("pb_save_areas")
        self.horizontalLayout_13.addWidget(self.pb_save_areas)
        self.pb_active_areas = QtWidgets.QPushButton(self.tab_2)
        self.pb_active_areas.setObjectName("pb_active_areas")
        self.horizontalLayout_13.addWidget(self.pb_active_areas)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.te_number_objects = QtWidgets.QTextEdit(self.tab_2)
        self.te_number_objects.setObjectName("te_number_objects")
        self.verticalLayout_8.addWidget(self.te_number_objects)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pb_reset_areas = QtWidgets.QPushButton(self.tab_2)
        self.pb_reset_areas.setObjectName("pb_reset_areas")
        self.horizontalLayout_14.addWidget(self.pb_reset_areas)
        self.pb_save_objects_number = QtWidgets.QPushButton(self.tab_2)
        self.pb_save_objects_number.setObjectName("pb_save_objects_number")
        self.horizontalLayout_14.addWidget(self.pb_save_objects_number)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.cb_display_analysis = QtWidgets.QCheckBox(self.layoutWidget1)
        self.cb_display_analysis.setChecked(True)
        self.cb_display_analysis.setObjectName("cb_display_analysis")
        self.verticalLayout_4.addWidget(self.cb_display_analysis)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_stop.setObjectName("pb_stop")
        self.horizontalLayout_6.addWidget(self.pb_stop)
        self.pbGo = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbGo.setObjectName("pbGo")
        self.horizontalLayout_6.addWidget(self.pbGo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_video = QtWidgets.QAction(MainWindow)
        self.actionOpen_video.setObjectName("actionOpen_video")
        self.actionBackground = QtWidgets.QAction(MainWindow)
        self.actionBackground.setObjectName("actionBackground")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFrame_width = QtWidgets.QAction(MainWindow)
        self.actionFrame_width.setObjectName("actionFrame_width")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_directory_of_images = QtWidgets.QAction(MainWindow)
        self.actionLoad_directory_of_images.setObjectName("actionLoad_directory_of_images")
        self.menuFile.addAction(self.actionOpen_video)
        self.menuFile.addAction(self.actionLoad_directory_of_images)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionFrame_width)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "TextLabel"))
        self.label2.setText(_translate("MainWindow", "TextLabel"))
        self.lb_total_frames_nb.setText(_translate("MainWindow", "Number of frames: "))
        self.label.setText(_translate("MainWindow", "current frame"))
        self.pb_1st_frame.setText(_translate("MainWindow", "Go to 1st frame"))
        self.pb_next_frame.setText(_translate("MainWindow", "next frame"))
        self.label_11.setText(_translate("MainWindow", "frame number"))
        self.le_goto_frame.setText(_translate("MainWindow", "1"))
        self.pb_goto_frame.setText(_translate("MainWindow", "Go to"))
        self.label_10.setText(_translate("MainWindow", "Step"))
        self.pb_backward.setText(_translate("MainWindow", "go backward"))
        self.pb_forward.setText(_translate("MainWindow", "go forward"))
        self.label_9.setText(_translate("MainWindow", "Image treatment"))
        self.lb_threshold.setText(_translate("MainWindow", "threshold"))
        self.label_8.setText(_translate("MainWindow", "Blur"))
        self.cb_invert.setText(_translate("MainWindow", "Invert"))
        self.cb_background.setText(_translate("MainWindow", "Substract background"))
        self.label_5.setText(_translate("MainWindow", "Objects"))
        self.pb_define_arena.setText(_translate("MainWindow", "Define arena"))
        self.pb_clear_arena.setText(_translate("MainWindow", "Clear arena"))
        self.label_12.setText(_translate("MainWindow", "Filters"))
        self.label_3.setText(_translate("MainWindow", "min obj size"))
        self.label_4.setText(_translate("MainWindow", "max obj size"))
        self.label_7.setText(_translate("MainWindow", "Number of largest objects"))
        self.label_13.setText(_translate("MainWindow", "Max object extension"))
        self.lb_all.setText(_translate("MainWindow", "All"))
        self.lb_filtered.setText(_translate("MainWindow", "Filtered"))
        self.cb_record_xy.setText(_translate("MainWindow", "record objects coordinates"))
        self.pb_reset_xy.setText(_translate("MainWindow", "Reset"))
        self.pb_save_xy.setText(_translate("MainWindow", "Save results"))
        self.pb_plot_path.setText(_translate("MainWindow", "Plot path"))
        self.pb_plot_xy_density.setText(_translate("MainWindow", "plot XY density"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Objects coordinates"))
        self.cb_record_number_objects.setText(_translate("MainWindow", "Record number of objects(s) in areas"))
        self.label_2.setText(_translate("MainWindow", "Areas"))
        self.pb_add_area.setText(_translate("MainWindow", "Add area"))
        self.pb_remove_area.setText(_translate("MainWindow", "Remove selected area"))
        self.pb_open_areas.setText(_translate("MainWindow", "Load areas from disk"))
        self.pb_save_areas.setText(_translate("MainWindow", "Save areas to disk"))
        self.pb_active_areas.setText(_translate("MainWindow", "Activate areas"))
        self.label_6.setText(_translate("MainWindow", "Number of object(s) in areas"))
        self.pb_reset_areas.setText(_translate("MainWindow", "Reset"))
        self.pb_save_objects_number.setText(_translate("MainWindow", "Save results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Area"))
        self.cb_display_analysis.setText(_translate("MainWindow", "Display analysis"))
        self.pb_stop.setText(_translate("MainWindow", "Stop"))
        self.pbGo.setText(_translate("MainWindow", "Run analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_video.setText(_translate("MainWindow", "Open video"))
        self.actionBackground.setText(_translate("MainWindow", "background"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionFrame_width.setText(_translate("MainWindow", "Frame width"))
        self.actionAbout.setText(_translate("MainWindow", "About DORIS"))
        self.actionLoad_directory_of_images.setText(_translate("MainWindow", "Load directory of images"))

